{"name": "Негативный сценарий: авторизация под несуществующим пользователем", "status": "passed", "description": "Проверяем,что нельзя авторизоваться под несуществующим пользователем", "steps": [{"name": "Отправляем запрос на авторизацию под несуществующим пользователем", "status": "passed", "start": 1744340811554, "stop": 1744340811786}, {"name": "Проверяем наличие текста об ошибке и статус", "status": "passed", "start": 1744340811786, "stop": 1744340811786}], "start": 1744340811554, "stop": 1744340811787, "uuid": "11c4a2bb-5c0d-4b53-95a0-6acb2dfb7f95", "historyId": "f2429c84e0b6de7cd14341220fc2037d", "testCaseId": "f2429c84e0b6de7cd14341220fc2037d", "fullName": "tests.test_login_courier.TestLoginCourier#test_cant_login_courier_has_not_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-MSISGTMAM5B"}, {"name": "thread", "value": "11716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}